"""rename popularity score to product sales

Revision ID: 098011356178
Revises: 
Create Date: 2024-08-21 14:17:04.300471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098011356178'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_sales', sa.Integer(), nullable=True))
        batch_op.drop_column('popularity_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('popularity_score', sa.INTEGER(), nullable=True))
        batch_op.drop_column('product_sales')

    # ### end Alembic commands ###
